# Generated by Django 3.2 on 2021-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
