# Generated by Django 3.2 on 2021-05-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project', verbose_name='project'),
        ),
    ]
