# Generated by Django 3.2 on 2021-05-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210505_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='case_study',
            new_name='value_proposition',
        ),
    ]
