# Generated by Django 3.2 on 2021-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_case_study_project_value_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
